### ISSUE TITLE
An aberration in benchmark results

### ISSUE THREAD

**Issue by harendra-kumar** [lehins/haskell-scheduler#3]
I noticed that for one of the benchmarks streamly's results did not seem as I expected. So I ran the benchmarks on my machine and got much better results. Not sure if this is a run-to-run aberration or just because of a difference in hardware. Your results are:

```
enchmarking map/Fib(2000)/scheduler/traverseConcurrently
time                 13.59 ms   (12.70 ms .. 14.58 ms)
                     0.978 R²   (0.963 R² .. 0.989 R²)
mean                 13.89 ms   (13.33 ms .. 14.66 ms)
std dev              1.594 ms   (1.131 ms .. 2.212 ms)
variance introduced by outliers: 56% (severely inflated)

benchmarking map/Fib(2000)/unliftio/pooledTraverseConcurrently
time                 7.987 ms   (7.134 ms .. 8.638 ms)
                     0.956 R²   (0.925 R² .. 0.982 R²)
mean                 7.888 ms   (7.508 ms .. 8.551 ms)
std dev              1.459 ms   (1.020 ms .. 2.173 ms)
variance introduced by outliers: 81% (severely inflated)

benchmarking map/Fib(2000)/streamly/mapM
time                 19.11 ms   (16.77 ms .. 21.11 ms)
                     0.941 R²   (0.882 R² .. 0.979 R²)
mean                 22.59 ms   (20.54 ms .. 26.62 ms)
std dev              6.343 ms   (1.834 ms .. 9.521 ms)
variance introduced by outliers: 90% (severely inflated)
```

Results on my machine are:

```
benchmarking map/Fib(2000)/scheduler/traverseConcurrently
time                 10.15 ms   (8.543 ms .. 11.76 ms)
                     0.791 R²   (0.619 R² .. 0.910 R²)
mean                 10.33 ms   (9.360 ms .. 11.55 ms)
std dev              3.126 ms   (2.347 ms .. 3.916 ms)
variance introduced by outliers: 93% (severely inflated)
                             
benchmarking map/Fib(2000)/unliftio/pooledTraverseConcurrently
time                 6.002 ms   (4.744 ms .. 7.231 ms)
                     0.707 R²   (0.525 R² .. 0.851 R²)
mean                 5.938 ms   (4.996 ms .. 7.316 ms)
std dev              3.071 ms   (1.868 ms .. 4.862 ms)
variance introduced by outliers: 97% (severely inflated)
                             
benchmarking map/Fib(2000)/streamly/mapM
time                 7.421 ms   (5.925 ms .. 8.972 ms)
                     0.730 R²   (0.589 R² .. 0.860 R²)
mean                 7.846 ms   (6.888 ms .. 9.286 ms)
std dev              3.356 ms   (2.338 ms .. 5.446 ms)
variance introduced by outliers: 97% (severely inflated)
```

**Comment by lehins** [comment]
That's interesting. It might be difference in hardware, but it also might be that the OS and the compiler for that OS has something to do with that as well. From what I know you are running on a Mac, right? My original benchmarks where produced with `Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz` on an Ubuntu 18.04 LTS

I ran same the benchmarks again on a more powerful server, that also runs Ubuntu 18.04 LTS but has a better processor `Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz` and got these results `¯\_(ツ)_/¯`
```
Benchmark scheduler: RUNNING...
benchmarking map/Fib(2000)/scheduler/traverseConcurrently
time                 5.319 ms   (4.429 ms .. 5.947 ms)
                     0.846 R²   (0.688 R² .. 0.960 R²)
mean                 7.612 ms   (6.567 ms .. 9.808 ms)
std dev              5.034 ms   (2.506 ms .. 8.563 ms)
variance introduced by outliers: 97% (severely inflated)

benchmarking map/Fib(2000)/unliftio/pooledTraverseConcurrently
time                 3.202 ms   (3.035 ms .. 3.353 ms)
                     0.975 R²   (0.948 R² .. 0.992 R²)
mean                 3.421 ms   (3.286 ms .. 4.003 ms)
std dev              678.3 μs   (253.4 μs .. 1.179 ms)
variance introduced by outliers: 89% (severely inflated)

benchmarking map/Fib(2000)/streamly/mapM
time                 14.03 ms   (12.70 ms .. 15.44 ms)
                     0.932 R²   (0.837 R² .. 0.976 R²)
mean                 12.51 ms   (11.77 ms .. 14.06 ms)
std dev              3.067 ms   (1.919 ms .. 5.060 ms)
variance introduced by outliers: 88% (severely inflated)

benchmarking map/Fib(2000)/async/mapConcurrently
time                 21.03 ms   (17.37 ms .. 23.25 ms)
                     0.907 R²   (0.639 R² .. 0.998 R²)
mean                 23.49 ms   (21.53 ms .. 30.86 ms)
std dev              8.028 ms   (822.7 μs .. 14.61 ms)
variance introduced by outliers: 94% (severely inflated)
```

**Comment by harendra-kumar** [comment]
It could be due to processor caching/prefetching characteristics working well for one library and not for the other. One difference that I can see is that by default streamly auto-scales the threads rather than fixing them to num capabilities, I did not care to fix it because streamly auto-scales pretty well. Another thing that I notice is that the difference is significant only in the Fib(2000) benchmark, not sure why is that.

**Comment by lehins** [comment]
Maybe. At the same time implementation of `fib` might also have some impact on the benchmark variance between different hardware+OS. Who knows. I don't really feel like debugging this. If you'd like me to remove `streamly` from that benchmark, I'll have no problem with that. Or if you'd like to switch to some other function instead of `fib`, I'd be fine with that too, just send a PR I'll happily accept it. (That `fib` package seems extremely new and isn't in any stackage snapshots, so I'll be fine with loosing it ;)
I'll let you decide what you wanna do with this ticket :)

**Comment by harendra-kumar** [comment]
It may be that fib is not as efficient for streamly for some reason. If that's the case then the difference is not really because of concurrency overhead but because of the inefficiency of serial execution itself. Anyway, its no big deal, let it be the way it is.
